FOLDERS = cpp cppinternals gcc gccgo gccint gfortran libgomp libitm libquadmath

default: html latexpdf

.PHONY: html
html:
	for dir in $(FOLDERS); do $(MAKE) -C $$dir html; done

.PHONY: latexpdf
latexpdf:
	for dir in $(FOLDERS); do $(MAKE) -C $$dir latexpdf; done
