name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: opensuse/tumbleweed

    steps:
      - run: zypper -n install
              python3-pip
              python3-ruff
              tar gzip

      - uses: actions/checkout@v3
      - run: flake8
      - run: ruff check .
      - run: pip install --break-system-packages pyupgrade
      - run: pyupgrade --py310-plus *py
